name: ssh-test

on: 
  push: 
    branches: [ "main" ]

jobs: 
  build:
    name: Build
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Dump MySQL database
        run: |
          export MYSQL_DATABASE_NAME=temp  
          export MYSQL_USER=${{ secrets.MYSQL_ID }} 
          export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          export DATE=$(date "+%Y%m%d")

          mysqldump -u $MYSQL_USER -p${MYSQL_PASSWORD} ${MYSQL_DATABASE_NAME} > /home/test/${DATE}_backup.sql
          zip -P ${MYSQL_PASSWORD} /home/test/${DATE}_backup.zip /home/test/${DATE}_backup.sql
          mv /home/test/${DATE}_backup.zip /home/test/backup/${DATE}_backup.zip
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2
      - name: Sync with S3
        run: |
          export DATE=$(date "+%Y%m%d")
          aws s3 sync /home/test/backup s3://s3backup-test
      - name: End
        run: |
          export DATE=$(date "+%Y%m%d")
          rm -rf /home/test/${DATE}_backup.sql
