name: ssh-test

on: 
  push: 
    branches: [ "main" ]

jobs: 
  build:
    name: Build
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Dump MySQL database
        run: |
          export MYSQL_DATABASE_NAME=temp  
          export MYSQL_USER=${{ secrets.MYSQL_ID }} 
          export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          export DATE=$(date "+%Y%m%d")

          mysqldump -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE_NAME > $DATE_backup.sql
      - name: S3 sync 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 sync ./build s3://s3backup-test
      - name: End
        run: rm -f /home/test/${date}_backup.sql
