name: ssh-test

on: 
  push: 
    branches: [ "main" ]

jobs: 
  build:
    name: Build
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Echo Message
        run: echo "하이" > test.txt
